source 'https://rubygems.org'

gem 'rails', '4.2.8'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'active_model_serializers'

group :development, :test do
  gem 'byebug'
  gem 'rspec-rails'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'chromedriver-helper'
  gem 'pry'
end

group :development do
  gem 'web-console', '~> 2.0'
end

gem 'webpacker', github: 'rails/webpacker'
gem 'react_webpack_rails', path: '../../'
gem 'rwr-view_helpers'
